apiVersion: v1
kind: Service
metadata:
  name: <app-name>-service
spec:
  selector:
    app: <app-name>
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
