apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: master-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meldaugherty/dotnet-app-gitops
    targetRevision: HEAD
    path: argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
