apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
spec:
  template:
    spec:
      containers:
      - name: dotnet-app
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
