apiVersion: apps/v1
kind: Deployment
metadata:
  name: <app-name>
spec:
  template:
    spec:
      containers:
      - name: <app-name>
        env:
        - name: ENVIRONMENT
          value: "Development"
