apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-app
  labels:
    app: dotnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-app
  template:
    metadata:
      labels:
        app: dotnet-app
    spec:
      imagePullSecrets:
        - name: gh-registry
      containers:
      - name: dotnet-app
        image: ghcr.io/meldaugherty/dotnet-codebase-test:latest
        ports:
        - containerPort: 5000
        - containerPort: 5001
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:5000;https://0.0.0.0:5001"
          - name: ASPNETCORE_URLS
            value: "http://0.0.0.0:5000;https://0.0.0.0:5001"