apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
images:
- name: ghcr.io/meldaugherty/dotnet-codebase-test
  newTag: sha-bbe56dd9ffed5985beb6a17f7579d5e9f5a0627b
patchesStrategicMerge:
- deployment.yaml