apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
images:
- name: ghcr.io/meldaugherty/dotnet-codebase-test
  newTag: 23e206604a06c944294b5282f7e8036ce9ea36c6
patchesStrategicMerge:
- deployment.yaml