apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
- ../../base
images:
- name: ghcr.io/meldaugherty/dotnet-codebase-test
  newTag: sha-daa9de6579d118fc9844c5449222210735ab97b8
patchesStrategicMerge:
- deployment.yaml